
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: smartide-docs
      webide-port: 6800
      ide-type: vscode
      volumes: 
        git-config: true
        ssh-key: true
      command:
        - git submodule update --init --recursive
        - cd docs
        - npm install
    services:
      smartide-docs:
        image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-golang:1.17.4-latest
        restart: always
        environment:
          ROOT_PASSWORD: root123
        volumes:
          - .:/home/project
          - /var/run/docker.sock:/var/run/docker.sock
        expose:
          - 1313
        ports:
          - 1313:1313
        networks:
          - smartide-network

    networks:
      smartide-network:
        external: true
