###########################################################################
# SmartIDE - Dev Containers
# Copyright (C) 2023 leansoftX.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################

FROM ubuntu:20.04

# 所有操作都是非交互式的
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ Asia/Shanghai
#git中文乱码问题
ENV LESSCHARSET=utf-8

# sshd
RUN mkdir /var/run/sshd && \
    apt-get update && \
    apt-get -y install --no-install-recommends openssh-server apache2-utils ca-certificates lsof curl wget git sudo && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

# 安装根证书
#RUN apt-get -qq update && \
#    apt-get -qq install -y --no-install-recommends ca-certificates curl

# 暴露ssh端口
EXPOSE 22

# install smartide (build version)
COPY smartide-linux /usr/local/bin/smartide 

# install kubectl
RUN mkdir ~/.ide && \
    wget --no-check-certificate "https://smartidedl.blob.core.chinacloudapi.cn/kubectl/v1.23.0/bin/linux/amd64/kubectl" -O ~/.ide/kubectl && \
    chmod +x ~/.ide/kubectl 
    
# install smartide agent
RUN wget --no-check-certificate 'https://smartidedl.blob.core.chinacloudapi.cn/smartide-agent/latest/smartide-agent-linux' -O /usr/local/bin/smartide-agent

# COPY smartide-linux /usr/local/bin/smartide
RUN cp /usr/local/bin/smartide /usr/local/bin/se  && \
    chmod +x /usr/local/bin/smartide && \
    chmod +x /usr/local/bin/se

COPY entrypoint_base.sh /idesh/entrypoint_base.sh
RUN chmod +x /idesh/entrypoint_base.sh

ENTRYPOINT ["/idesh/entrypoint_base.sh"]
