apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template-smartide-cli
spec:
  params:
    - name: COMMAND
      description: smartide command
      default:
    - name: ARGS
      description: command args
      default:
    - name: HOST
      description: SSH host
      default:
    - name: SSH_USER_NAME
      description: The ssh login user name
      default:
    - name: SSH_USER_PASSWORD
      description: ssh user login password
      default:
    - name: GIT_CLONE_URL
      description: The git clone url
      default:

    - name: SERVER_WORK_SPACE_ID
      description: 服务端工作区ID
      default:
    - name: SERVER_WORK_SPACE_NO
      description: 服务端工作区NO
      default:
    - name: SERVER_USER_NAME
      description: 服务端用户名
      default:
    - name: SERVER_USER_GUID
      description: 服务端用户GUID
      default:
    - name: SERVER_HOST
      description: server 登录地址
      default:
    - name: SERVER_TOKEN
      description: 服务端TOKEN
      default:
    - name: CLI_VERSION
      description: cli版本号
      default:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-smartide-cli-run-
      spec:
        pipelineRef:
          name: pipeline-smartide-cli
        params:
          - name: COMMAND
            value: $(tt.params.COMMAND)
          - name: ARGS
            value: $(tt.params.ARGS)
          - name: HOST
            value: $(tt.params.HOST)
          - name: SSH_USER_NAME
            value: $(tt.params.SSH_USER_NAME)
          - name: SSH_USER_PASSWORD
            value: $(tt.params.SSH_USER_PASSWORD)
          - name: GIT_CLONE_URL
            value: $(tt.params.GIT_CLONE_URL)

          - name: SERVER_WORK_SPACE_ID
            value: $(tt.params.SERVER_WORK_SPACE_ID)
          - name: SERVER_WORK_SPACE_NO
            value: $(tt.params.SERVER_WORK_SPACE_NO)
          - name: SERVER_USER_NAME
            value: $(tt.params.SERVER_USER_NAME)
          - name: SERVER_USER_GUID
            value: $(tt.params.SERVER_USER_GUID)
          - name: SERVER_HOST
            value: $(tt.params.SERVER_HOST)
          - name: SERVER_TOKEN
            value: $(tt.params.SERVER_TOKEN)
          - name: CLI_VERSION
            value: $(tt.params.CLI_VERSION)
