FROM registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-v2-vscode-vmlc

USER root
RUN apt-get update
RUN apt-get install -y wget apt-transport-https software-properties-common
RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y powershell
RUN rm -rf packages-microsoft-prod.deb

COPY dotnet.service /lib/systemd/system/
COPY install-dotnet.sh /idesh/install-dotnet.sh

RUN chmod +x /idesh/install-dotnet.sh &&                               \
    ln -sf /lib/systemd/system/dotnet.service                    \
       /etc/systemd/system/multi-user.target.wants/dotnet.service