#################################################
# SmartIDE Developer Container Image
# Licensed under GPL v3.0
# Copyright (C) leansoftX.com
#################################################

FROM registry.cn-hangzhou.aliyuncs.com/smartide/smartide-dotnet-v2-vmlc:6.0

USER root

RUN mkdir $HOME/dotnet_install && cd $HOME/dotnet_install && \
    curl -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh && \
    sudo bash install-dotnet-preview.sh && \
    dotnet --list-sdks

# RUN apt-get update && \
#     apt-get install -y wget apt-transport-https software-properties-common
# RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
# RUN dpkg -i packages-microsoft-prod.deb && \
#     apt-get update && \
#     apt-get install -y powershell && \
#     rm -rf packages-microsoft-prod.deb

# RUN apt-get update && \ 
#     apt-get install -y apt-transport-https && \
#     apt-get install -y dotnet-sdk-7.0 && \
#     apt-get install -y aspnetcore-runtime-7.0 && \
#     apt-get autoremove -y && \
#     rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

# ENV DOTNET_ROOT=$HOME/dotnet
# ENV PATH=$HOME/dotnet:$PATH
# ENV PATH=$HOME/.dotnet/tools:$PATH
# ENV DOTNET_CLI_TELEMETRY_OPTOUT=false